config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :accounts, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  mount Commontator::Engine => '/commontator'

  
  get '/auth/:provider/callback', to: 'omniauth#create'
  post '/auth/:provider/callback', to: 'omniauth#create'
  get '/auth/failure', to: redirect('/')

  scope "", default_format: :json do
    post "/panda/authorize_upload", to: "panda#authorize_upload"
    post "/panda/notifications", to: "panda#notifications"
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :unpublish, on: :member
      put :restore, on: :member
      delete :really_destroy, on: :member 

      resource :video do
        get :refresh, on: :collection
      end
    end

    namespace :pages do
      resource :imprint
    end
    
    resource :profile
    resource :setting
    resources :orders, only: [:index, :new, :create]

    get '' => 'posts#index'
  end
  
  resources :accounts do
    put :follow, on: :member
    put :unfollow, on: :member
    get :videos, on: :member
    get :imprint, on: :member
  end

  resources :posts
  resource :profile

  resources :pages, only:[] do
    collection do
      get :imprint
      get :terms_and_conditions
      get :contact
      get :promotion
    end
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
  end

  root to: "posts#index"

end

app/controllers/accounts/profiles_controller.rb
class Accounts::ProfilesController < Accounts::BaseController
  
  def index
    @profile = current_account.account_profile
  end

  def show
    @profile = current_account.account_profile
  end

  def new
    @profile = AccountProfile.new
    @profile.account = current_account
  end

  def create
    @profile = AccountProfile.create(profile_params)
    @profile.account = current_account
    @profile.save

    redirect_to accounts_profile_path
  end

  def edit
    @profile = current_account.account_profile
  end

  def update
    @profile = current_account.account_profile
    @profile.update_attributes(profile_params)
    redirect_to accounts_profile_path
  end

  private

  def profile_params
      params.require(:account_profile).permit(:first_name,:last_name, :avatar)
  end

end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < Admin::BaseController
  set_tab :profile
  
  def index
    @profile = current_account.profile
  end

  def show
    @profile = current_account.profile
    @account = current_account
  end

  def new
    @profile = AccountProfile.new
    @profile.account = current_account
  end

  def create
    @profile = AccountProfile.create(profile_params)
    @profile.account = current_account
    @profile.save

    redirect_to account_path(current_account)
  end

  def edit
    @profile = current_account.profile
  end

  def update
    @profile = current_account.profile
    @profile.update_attributes(profile_params)

    @profile.private_fields = profile_params[:private_fields]
    @profile.save

    redirect_to account_path(current_account)
  end

  private

  def profile_params
      params.require(:account_profile).permit(:first_name,:last_name, :avatar, :remove_avatar, :description, :private_fields=>[])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :authenticate_account!
  
  layout 'bgwhite'
  
  def show
    @account = @current_author
    @profile = @current_author.profile
  end
  
end

app/views/admin/profiles/_form.html.haml
= bootstrap_form_for(@profile, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", url: admin_profile_path) do |f|

  .form-group
    %label.control-label.col-sm-3
      Email
    .col-sm-9
      .form-control
        = @profile.account.email
      %p.help-block
        Email field is not editable.

      %p
        = check_box_tag 'account_profile[private_fields][]', 'email', @profile.email_private?, id: 'account_profile_email_private'
        %label{ for: 'account_profile_email_private' }
          make private

  = f.text_field :first_name
  = f.text_field :last_name
  - if !@profile.avatar.blank?
    = f.form_group do
      = image_tag(@profile.avatar_url, :class => 'img-responsive editprofileimg')
      = f.check_box :remove_avatar
  - else
    = f.file_field :avatar

  = f.text_area :description
  %hr
  = f.form_group do
    = f.submit "Save", class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn btn-default'

app/views/admin/profiles/edit.html.haml
%h2 Edit Profile
.shortline.mb2
= render "form"

app/views/admin/profiles/show.html.haml
%h2 Account Profile
.shortline.mb2

%p
  %strong
    Name:
  = current_account.full_name
- if !current_account.profile.email_private?
  %p
    %strong Email:
    = current_account.email
%p
  = image_tag(current_account.profile.avatar_url) if current_account.profile.avatar?

%p
  - if current_account.profile.blank?
    = link_to "Create Profile", new_admin_profile_path, class: 'btn btn-primary'
  - else
    = link_to "Edit Profile", edit_admin_profile_path, class: 'btn btn-primary'