config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :accounts, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  mount Commontator::Engine => '/commontator'

  
  get '/auth/:provider/callback', to: 'omniauth#create'
  post '/auth/:provider/callback', to: 'omniauth#create'
  get '/auth/failure', to: redirect('/')

  scope "", default_format: :json do
    post "/panda/authorize_upload", to: "panda#authorize_upload"
    post "/panda/notifications", to: "panda#notifications"
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :unpublish, on: :member
      put :restore, on: :member
      delete :really_destroy, on: :member 

      resource :video do
        get :refresh, on: :collection
      end
    end

    namespace :pages do
      resource :imprint
    end
    
    resource :profile
    resource :setting
    resources :orders, only: [:index, :new, :create]

    get '' => 'posts#index'
  end
  
  resources :accounts do
    put :follow, on: :member
    put :unfollow, on: :member
    get :videos, on: :member
    get :imprint, on: :member
  end

  resources :posts
  resource :profile

  resources :pages, only:[] do
    collection do
      get :imprint
      get :terms_and_conditions
      get :contact
      get :promotion
    end
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
  end

  root to: "posts#index"

end

app/models/order.rb
require 'active_merchant/billing/rails'

class Order < ActiveRecord::Base
  include TokenGenerator

  belongs_to :account
  has_one :billing_address, class_name: 'Address', as: :addressable, inverse_of: :addressable, dependent: :destroy
  accepts_nested_attributes_for :billing_address

  scope :inatec, -> { where(payment_method: 'inatec') }
  scope :not_baio, -> { where("payment_method != 'baio'") }
  scope :most_recent, -> { order('created_at DESC') }

  enum status: { created: 0, active: 1, inactive: 2, cancelled: 3, failed: 4 }
  serialize :info, Hash
  mount_uploader :invoice_file, InvoiceUploader
  attr_accessor :number, :year, :month, :verification_value, :ip

  monetize :subtotal_cents, disable_validation: true
  monetize :tax_cents, disable_validation: true
  monetize :total_cents, disable_validation: true

  validates :account, :plan, :plan_type, :status, :payment_method, presence: true

  def plan
    Plan.by_plan_type(plan_type)
  end

  def tax_percentage
    tax_cents * 100.0 / subtotal_cents
  end

  def calculate_prices
    self.subtotal_cents = plan[:price_cents]
    self.total_cents = ((subtotal_cents / 100.0) * Rails.application.secrets[:tax_percentage].to_f) + subtotal_cents
    self.tax_cents = total_cents - subtotal_cents
  end

  def create_payment!
    self.payment_method = 'inatec'
    self.card_brand = credit_card.brand
    self.last_4_digits = credit_card.display_number
    calculate_prices unless total_cents

    unless valid? && check_credit_card_validation
      self.status = :failed
      raise 'Order validation failed'
    end
    save!

    response = ::INATEC_GATEWAY.authorize_with_recurring(total_cents, credit_card, purchase_options)
    process_response(response)

    if active?
      inactive_others
      generate_invoice_and_send_mail
    else
      raise 'Not active payment'
    end
  end

  #TODO def create_recurring_payment!
  #   response = ::INATEC_GATEWAY.charge_recurring(total_cents, transaction_id, purchase_options)
  #   process_response(response)
  #
  #   generate_invoice_and_send_mail
  # end

  def self.generate_pdf(order_id)
    order = Order.find(order_id)
    return if order.baio_order?

    FileUtils.mkpath("tmp/orders")
    tmp_path = File.join("tmp/orders", order.invoice_filename)

    pdf_content = PdfCreator.render_invoice(order)
    File.open(tmp_path, 'wb'){|f| f.write pdf_content }

    order.invoice_file = File.open(tmp_path)
    order.save
    FileUtils.rm(tmp_path)

    AccountMailer.payment_success_mail(order.id).deliver
  end

  def invoice_id
    'VP7-%05d' % id
  end

  def invoice_filename
    "#{invoice_id}.pdf"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def check_credit_card_validation
    success = true

    unless credit_card.valid?
      success = false

      credit_card.errors.each do |k,v|
        unless v.blank?
          errors.add(k, v.first)
          errors.add(:number, 'is invalid') if k == 'brand'
        end
      end
    end

    success
  end

  def baio_order?
    payment_method == 'baio'
  end

  def self.create_baio_order(account)
    order = account.orders.create plan_type: 'expert', status: :active, payment_method: 'baio', expired_at: 100.years.since
    order.inactive_others if order.persisted?
    order
  end

  def inactive_others
    account.orders.where('id != ?', id).active.update_all(status: Order.statuses[:inactive])
  end

  private

  def process_response(response)
    if response.success?
      self.info = response.params
      self.transaction_id = response.params["transid"].first if self.transaction_id.blank?
      self.expired_at = Plan::DURATION.months.since
      self.status = :active
      save!
    else
      self.status = :failed
      errors.add :base, response.message
      raise "Payment transaction failed: #{response.message}"
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      first_name:         first_name,
      last_name:          last_name,
      month:              month,
      year:               year,
      verification_value: verification_value,
      number:             number
    )
  end

  def purchase_options
    raise 'Must be persisted' unless persisted?

    {
      order_id:     invoice_id,
      ip:           ip,
      first_name:   account.profile.first_name,
      last_name:    account.profile.last_name,
      description:  'Videopage7 plan purchase',
      email:        account.email,
      currency:     Rails.application.secrets[:currency_code],
      address: {
        zip:        billing_address.postal_code,
        street:     billing_address.address_1,
        city:       billing_address.city,
        country:    billing_address.billing_country
      }
    }
  end

  def generate_invoice_and_send_mail
    Order.delay.generate_pdf(self.id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  skip_before_action :authenticate_account!, only: :new

  set_tab :orders

  def index
    @orders = current_account.orders.order("created_at desc")

    # render layout: false
  end

  def new
    selected_plan = Plan.by_plan_type(params[:plan])
    if current_account && selected_plan
      current_account.check_upgrade_plan!(selected_plan)
      @order = current_account.orders.build plan_type: params[:plan],
                                            first_name: current_account.profile.first_name,
                                            last_name: current_account.profile.last_name
      @order.calculate_prices
      @order.build_billing_address
    else
      render 'select_plan'
    end

  rescue => ex
    flash.now[:alert] = ex.message
    render 'select_plan'
  end

  def create
    @order = current_account.orders.build(order_params)

    begin
      current_account.check_upgrade_plan!(@order.plan)
    rescue => ex
      redirect_to new_admin_order_path, alert: ex.message
      return
    end

    @order.create_payment!
    redirect_to admin_orders_path, notice: 'Your order is created.'

  rescue => ex
    if @order
      Rails.logger.error @order.errors.to_hash.inspect
      @order.destroy if @order.persisted?
    end

    Rails.logger.error ex.inspect
    Rails.logger.error ex.backtrace.join("\n")

    flash.now[:alert] = 'Sorry, payment is failed. Please try it again'
    render 'new'
  end
  
  private

  def order_params
    params.fetch(:order, {})
          .permit(:first_name, :last_name, :number, :year, :month, :verification_value, :plan_type,
                  billing_address_attributes: [:id, :address_1, :address_2, :city, :state, :postal_code, :country_code])
          .merge({ip: request.remote_ip})
  end
end

app/views/admin/orders/index.html.haml
= render 'admin/shared/setting_tabs'

%h2 Orders
.shortline.mb2

%div.table-responsive
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th Method
        %th Plan
        %th Sub total
        %th Tax
        %th Total
        %th Expired at
        %th Status
        %th Paid at
        %th Invoice
    %tbody
      - if @orders.count > 0
        - @orders.each do |order|
          %tr
            %td= order.payment_method
            %td= order.plan.name
            %td= money_with_cents_and_with_symbol order.subtotal
            %td= money_with_cents_and_with_symbol order.tax
            %td= money_with_cents_and_with_symbol order.total
            %td= order.expired_at
            %td
              - case order.status
              - when 'active'
                %span.label.label-success Active
              - when 'cancelled'
                %span.label.label-warning Canceled
              - when 'failed'
                %span.label.label-danger Failed
              - else
                %span.label.label-default= order.status.titleize
            %td= order.created_at.to_date
            %td
              /
                = order.id

              - if order.invoice_file.file
                = link_to 'Download Invoice', order.invoice_file.url, :class => 'btn btn-default btn-xs btn-action'

      - else
        %tr
          %td{colspan: 10} You have no orders

  .clearfix
  -#- if current_account.has_active_order? and current_account.active_order.payment_method != 'baio'
    .pull-right
      %i Please contact admin if you want to cancel active order


= link_to 'Upgrade your plan', new_admin_order_path, class: 'btn btn-primary'

app/views/admin/orders/invoice.pdf.haml
#invoice_content
  .row{style: "margin-bottom: 4em;"}
    .col-xs-6
      %h1
        = wicked_pdf_image_tag 'bonofa_logo.png', class: 'logo'
    .col-xs-6.text-right
      %h1 INVOICE
      %h3
        %span{style: "color: #aaa;"}= order.invoice_id
        | #{order.created_at.to_date.iso8601}
  .row{style: "margin-bottom: 2em;"}
    .col-xs-5
      .panel.panel-default
        .panel-heading
          %h4 From: BONOFA AG
        .panel-body
          %p
            Im Loch 11
            %br
            FL 9494 Schaan
            %br
            Liechtenstein
            %br
    .col-xs-5.col-xs-offset-2
      .panel.panel-default
        .panel-heading
          %h4
            To:
            = account.full_name
        .panel-body
          %p
            %strong
              = "Mr/Mrs. #{order.full_name}"
            %br
            = "#{billing_address.address_line1}"
            %br
            = "#{billing_address.address_line2}"
          %p
            %strong Kd-Nr. | Partner-ID
            - if account.promotion_code.present?
              %br
              = account.promotion_code
  / / end client details section
  %table.table.table-bordered
    %thead
      %tr
        %th
          %h4 Service / Date
        %th
          %h4 Description
        %th
          %h4 Hrs/Qty
        %th
          %h4 Rate/Price
        %th
          %h4 Sub Total
    %tbody
      %tr
        %td
          %strong Videopage7
          %br/
          %small= order.created_at.to_date.iso8601
        %td= "#{plan.name} Plan"
        %td.text-right 1
        %td.text-right= money_with_cents_and_with_symbol(order.subtotal)
        %td.text-right= money_with_cents_and_with_symbol(order.subtotal)
      %tr
        %td
        %td
        %td
        %td
        %td
  .row.text-right
    .col-xs-12
      %p
        Selected Payment method: Paid with #{order.card_brand} (#{order.last_4_digits})
  .row.text-right
    .col-xs-2.col-xs-offset-8
      %p
        %strong
          Sub Total :
          %br/
          TAX (#{percentage_with_symbol(order.tax_percentage)}):
          %br/
          Total :
          %br/
    .col-xs-2
      %strong
        = money_with_cents_and_with_symbol(order.subtotal)
        %br/
        = money_with_cents_and_with_symbol(order.tax)
        %br/
        = money_with_cents_and_with_symbol(order.total)
        %br/
  .row{style: "margin-top: 2em;"}
    .panel.panel-info
      .panel-body
        .col-xs-6
          %p
            %strong Bonofa AG
          %p Commerzbank Saarbrücken
          %p
            SWIFT: 590 400 00
            %br/
            Account Number: 536 1870800
          %p
            IBAN: DE 62 5904 0000 0536 1870 00
            %br/
            BIC: COBADEFFXXX
        .col-xs-6
          %p
            Öffentlichkeitsregister:
            %br/
            Grundbuch- und Öffentlichkeits- registeramt Vaduz
            %br/
            FL-0002.383.447-5
          %p Verwaltungsräte: Mag. jur. Gerd H. Jelenik, Thomas Kulla, Detlef Tilgenkamp
          %p Mehrwertsteuer-Nr.: 57 954 (LIECHTENSTEIN)
          %p
            Email: payment@bonofa.com
          %p
            Our general terms and conditions apply

app/views/admin/orders/new.html.haml
= render 'admin/shared/setting_tabs'

%h2 Purchase
.shortline.mb2

%legend Order Summary
.col-sm-12
  %div.table-responsive
    %table.table.table-bordered
      %tr
        %td Plan
        %td= @order.plan.name
      %tr
        %td Price
        %td= money_with_cents_and_with_symbol(@order.subtotal)
      %tr
        %td Tax (#{percentage_with_symbol(@order.tax_percentage)})
        %td= money_with_cents_and_with_symbol(@order.tax)
      %tr
        %td Total
        %td= money_with_cents_and_with_symbol(@order.total)




= bootstrap_form_for [:admin, @order], layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-8' do |f|
  = f.hidden_field :plan_type

  %legend Card Information
  = f.text_field :first_name, required: true
  = f.text_field :last_name, required: true
  = f.text_field :number, required: true, label: 'Card number'
  = f.select :year, (Date.today.year..(Date.today.year + 10)), required: true
  = f.select :month, (1..12), required: true
  = f.text_field :verification_value, required: true, label: 'CVV'

  %legend Billing Address
  = f.fields_for :billing_address do |a|
    = a.text_field :address_1, required: true
    = a.text_field :address_2
    = a.text_field :city, required: true
    = a.text_field :state, required: true
    = a.text_field :postal_code, required: true

    = a.form_group :country_code, label: { text: 'Country' } do
      = a.country_select :country_code, { prompt: 'Please select a country' }, required: true, class: 'form-control'

  %hr
  = f.form_group do
    = f.submit 'Process Payment', class: 'btn btn-primary', confirm: "Are you sure to create this order?"
    = link_to 'Cancel', admin_orders_path, class: 'btn btn-default'

app/views/admin/orders/select_plan.html.haml
- if current_account
  = render 'admin/shared/setting_tabs'

#plans
  %h2 Select Plan
  .shortline.mb2

  .row
    %ul.col-md-4
      %li.plan-head
        %h3 Free
      %li.plan-image
        = image_tag 'videopage7_free.png'
        %span.price
          %span= plan_price_with_symbol(Plan.free_plan.price_cents)
          %span.price-small year
      %li.yes
        Create ONE videopage
      %li.yes
        Use Your Own Domain
      %li.no
        Post Unlimited Videos (Maximum of 5)
      %li.yes
        500MB space
      %li.no
        Place Your Videos In "Successes" Category
      %li.no
        Upload Your Custom Logo
      %li.buy
        - case current_account && current_account.upgrade_plan_status(Plan.free_plan)
        - when :current
          = link_to 'Current plan', '#', class: 'btn disabled', disabled: true
        - else
          - if current_account
            = link_to "Can't upgrade", '#', class: 'btn disabled', disabled: true
          - else
            = link_to "REGISTER", new_account_session_path

    %ul.col-md-4
      %li.plan-head
        %h3 Pro
      %li.plan-image
        = image_tag 'videopage7_pro.png'
        %span.price
          %span= plan_price_with_symbol(Plan.pro_plan.price_cents)
          %span.price-small year
      %li.yes
        Create ONE videopage
      %li.yes
        Use Your Own Domain
      %li.yes
        Post Unlimited Videos
      %li.yes
        5GB space
      %li.yes
        Place Your Videos In "Successes" Category
      %li.yes
        Upload Your Custom Logo
      %li.buy
        - case current_account && current_account.upgrade_plan_status(Plan.pro_plan)
        - when :current
          = link_to 'Current plan', '#', class: 'btn disabled', disabled: true
        - when :can_upgrade
          = link_to "Upgrade to PRO", new_admin_order_path(plan: 'pro')
        - else
          = link_to "Can't upgrade", '#', class: 'btn disabled', disabled: true

    %ul.col-md-4
      %li.plan-head
        %h3 Expert
      %li.plan-image
        = image_tag 'videopage7_expert.png'
        %span.price
          %span= plan_price_with_symbol(Plan.expert_plan.price_cents)
          %span.price-small year
      %li.yes
        Create ONE videopage
      %li.yes
        Use Your Own Domain
      %li.yes
        Post Unlimited Videos
      %li.yes
        10GB space
      %li.yes
        Place Your Videos In "Successes" Category
      %li.yes
        Upload Your Custom Logo
      %li.buy
        - case current_account && current_account.upgrade_plan_status(Plan.expert_plan)
        - when :current
          = link_to 'Current plan', '#', class: 'btn disabled', disabled: true
        - when :can_upgrade
          = link_to "Upgrade to EXPERT", new_admin_order_path(plan: 'expert')
        - else
          = link_to "Can't upgrade", '#', class: 'btn disabled', disabled: true

  - if current_account
    .row.mt2
      .col-md-12.text-right
        = link_to 'Cancel', admin_orders_path, class: 'btn btn-default'