config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :accounts, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  mount Commontator::Engine => '/commontator'

  
  get '/auth/:provider/callback', to: 'omniauth#create'
  post '/auth/:provider/callback', to: 'omniauth#create'
  get '/auth/failure', to: redirect('/')

  scope "", default_format: :json do
    post "/panda/authorize_upload", to: "panda#authorize_upload"
    post "/panda/notifications", to: "panda#notifications"
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :unpublish, on: :member
      put :restore, on: :member
      delete :really_destroy, on: :member 

      resource :video do
        get :refresh, on: :collection
      end
    end

    namespace :pages do
      resource :imprint
    end
    
    resource :profile
    resource :setting
    resources :orders, only: [:index, :new, :create]

    get '' => 'posts#index'
  end
  
  resources :accounts do
    put :follow, on: :member
    put :unfollow, on: :member
    get :videos, on: :member
    get :imprint, on: :member
  end

  resources :posts
  resource :profile

  resources :pages, only:[] do
    collection do
      get :imprint
      get :terms_and_conditions
      get :contact
      get :promotion
    end
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
  end

  root to: "posts#index"

end

app/controllers/admin/pages/imprints_controller.rb
class Admin::Pages::ImprintsController < Admin::BaseController
  
  set_tab :page

  def update
    @page = current_account.pages.find_or_create_by(slug: 'imprint')
    if @page.update_attributes(page_params)
      flash[:success] = "Updated successfully."
    end
    redirect_to edit_admin_pages_imprint_path
  end

  def edit
    @page = current_account.pages.find_or_create_by(slug: 'imprint')
  end
  
  private

    def page_params
      params.require(:page).permit(:title,:content,:bootsy_image_gallery_id)
    end
end

app/views/admin/pages/imprints/_form.html.haml
= bootstrap_form_for(@page, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", url: admin_pages_imprint_path) do |f|
  = f.text_field :title
  .form-group
    %label.control-label.col-sm-3{:for => "page_content"} Content
    .col-sm-9
      = f.bootsy_area :content, class: 'form-control', rows: 20
  %hr
  = f.form_group do
    = f.submit "Save", class: 'btn btn-primary'
    = link_to 'Cancel', :back, class: 'btn btn-default'

app/views/admin/pages/imprints/edit.html.haml
= render 'admin/shared/setting_tabs'
%br

%h2 Edit Imprint
.shortline.mb2
= render "form"

app/views/admin/pages/imprints/new.html.haml
%h2 Create Profile
.shortline.mb2
= render "form"

app/views/admin/pages/imprints/show.html.haml
%h2 Account Setting
.shortline.mb2

%p
  %strong
    Blog alias:
  = @setting.blog_alias
%p
  %strong
    Blog enabled:
  = @setting.blog_enabled

%p
  = link_to "Edit Setting", edit_admin_setting_path