config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :accounts, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  mount Commontator::Engine => '/commontator'

  
  get '/auth/:provider/callback', to: 'omniauth#create'
  post '/auth/:provider/callback', to: 'omniauth#create'
  get '/auth/failure', to: redirect('/')

  scope "", default_format: :json do
    post "/panda/authorize_upload", to: "panda#authorize_upload"
    post "/panda/notifications", to: "panda#notifications"
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :unpublish, on: :member
      put :restore, on: :member
      delete :really_destroy, on: :member 

      resource :video do
        get :refresh, on: :collection
      end
    end

    namespace :pages do
      resource :imprint
    end
    
    resource :profile
    resource :setting
    resources :orders, only: [:index, :new, :create]

    get '' => 'posts#index'
  end
  
  resources :accounts do
    put :follow, on: :member
    put :unfollow, on: :member
    get :videos, on: :member
    get :imprint, on: :member
  end

  resources :posts
  resource :profile

  resources :pages, only:[] do
    collection do
      get :imprint
      get :terms_and_conditions
      get :contact
      get :promotion
    end
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_scope :account do
    get '/p/:referrer_code', to: 'registrations#promolink', as: 'promolink'
  end

  root to: "posts#index"

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :post
  belongs_to :account, counter_cache: true

  has_many :encodings, class_name: 'VideoEncoding', foreign_key: 'video_id', dependent: :destroy

  validates_presence_of :panda_video_id
  scope :encoded, -> { where(encoded: true) }

  after_destroy :delete_panda_video

  def panda_video
    @panda_video ||= Panda::Video.find(self.panda_video_id)
  end

  def panda_encodings
    @encodings ||= self.panda_video.encodings
  end

  def screenshots
    if self.panda_video_id
      @screenshots ||= self.encodings.first.screenshots
    else
      []
    end
  end

  def humanized_title
    return 'Untitled' if self.title.blank?
    self.title
  end

  def create_video_encoding(encoding)
    self.encodings.create_from_panda_encoding(encoding)
    self.width = encoding.width
    self.height = encoding.height
    self.file_size = encoding.file_size
    self.screenshot = encoding.screenshots.first
    self.encoded = true
    self.save
  end

  def refresh
    unless panda_encodings.blank?
      panda_encodings.each do |encoding|
        if encoding.status == "success"
          self.create_video_encoding(encoding)
        end
      end
    end
  end

  def self.accept_upload?(file_name)
    mime_type = Rack::Mime.mime_type(File.extname(file_name))
    mime_type.start_with? 'video'
  end

  private

  def delete_panda_video
    panda_video.delete
  end

end

app/controllers/accounts/videos_controller.rb
class Accounts::VideosController < Accounts::BaseController
  
  before_filter :load_video, only: [:show, :update, :edit, :destroy]
  before_filter :update_video_status, only: [:edit]

  def index
    @videos = current_account.videos.order("created_at").page(params[:page]).per(5)
  end

  def show
  end
  
  def edit
  end

  def new
    @video = Video.new
  end

  def update
    if @video.update(video_params)
      redirect_to accounts_videos_path
    else
      redirect_to edit_accounts_video_path(@video)
    end
  end

  def create
    @video = Video.new(video_params)
    @video.account = current_account
    if @video.save
      flash[:success] = "Video successfully updated"
      redirect_to accounts_videos_path
    else
      flash[:danger] = @video.errors.full_messages.to_sentence
      redirect_to new_accounts_video_path
    end
  end

  def destroy
    @video.destroy
    redirect_to accounts_videos_path
  end




  private

  def video_params
    params.require(:video).permit(:panda_video_id, :title, :screenshot, :profile)
  end

  def load_video
    @video = current_account.videos.find(params[:id])
  end

  def update_video_status
    unless @video.encoded
      unless @video.panda_video.status == 'fail'
        @video.encoded = true
      end
    end
  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  
  before_filter :load_post
  before_filter :load_video, only: [:update, :destroy, :show, :edit, :refresh]

  set_tab :video

  def new
    @video = Video.new
  end
  
  def show
  end
  
  def edit
  end

  def refresh
    @video.refresh
    redirect_to edit_admin_post_video_path(@post)
  end

  def update
    if @video.update(video_params)
      redirect_to edit_admin_post_path(@post)
    else
      render :edit
    end
  end

  def create
    @video = Video.new(video_params)
    @video.account = current_account
    @video.post = @post
    if @video.save
      flash[:success] = "Successfully uploaded a video, but it will take several minutes to encode."
    else
      flash[:danger] = @video.errors.full_messages.to_sentence
    end
    redirect_to edit_admin_post_path(@post)
  end

  def destroy
    @post.destroy
    flash[:danger] = "Deleted successfully"
    redirect_to admin_posts_path
  end


  private

  def video_params
    params.require(:video).permit(:panda_video_id)
  end

  def load_video
    @video = @post.video
  end

  def load_post
    @post = current_account.posts.find(params[:post_id])
  end
end

app/views/admin/videos/_form.html.haml
= render 'admin/posts/form_tabs'
.row.mb2.text-right
  .col-md-6
    .help
      %span Please choose a file that is under 200 MB.

= bootstrap_form_for [:admin, @post, @video], url: admin_post_video_path(@post), layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", html: { role: "form" } do |f|
  = f.hidden_field :panda_video_id
  - if @video.new_record?
    .row
      %label.control-label.col-sm-3
        File
      .col-sm-9
        #upload-error.label.label-danger(style="display:none;" )
          Not a video file
        .progress.progress-striped.active
          #progress-bar.progress-bar{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "45", :role => "progressbar", :style => "width: 0%"}
            %span.sr-only 0% Complete
        .clearfix
          #browse.btn.btn-primary Choose file
          #cancel-btn.btn.btn-danger Cancel

  - if @video.panda_video_id
    - unless @video.encoded?
      .alert.alert-info
        Video is still in encoding, It could take for a while. Please be patient.
    - else
      = f.form_group do
        %video{ poster: @video.screenshot, controls: true, width: @video.width, height: @video.height, autoplay: false }
          - @video.encodings.each do |encoding|
            %source{:src => encoding.url, :type => encoding.mime_type}/

      - @video.encodings.each do |encoding|
        = f.form_group do
          %strong
            = encoding.profile_name
          ,
          = "#{@video.width} x #{@video.height}"
          ,
          = number_to_human_size(encoding.file_size)

    = f.form_group do
      = link_to 'Back', edit_admin_post_path(@post), class: 'btn btn-default'
      = link_to 'Refresh', refresh_admin_post_video_path(@post), class: 'btn btn-warning'
      = link_to 'Remove Video', admin_post_video_path(@post), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" }


- if @video.new_record?
  = content_for :javascript do
    %script{:src => "//cdn.pandastream.com/u/2.3/panda-uploader.min.js"}
    :javascript
      var currentFile = null;
      var uploadCancelled = false;

      var upl = panda.uploader.init({
        'buttonId': 'browse',
        'onQueue': function(files) {
          $.each(files, function(i, file) {
            upl.setPayload(file, {'csrf': "#{ form_authenticity_token }"});
          });
          currentFile = null;
          uploadCancelled = false;
          $('#upload-error').hide();
        },
        'onStart': function(file) {
          console.log("onStart");
          currentFile = file;
        },
        'onProgress': function(file, percent) {
          // console.log("onProgress", percent, "%");
          $("#progress-bar").css("width", percent + "%");
        },
        'onSuccess': function(file, data) {
          console.log("onSuccess");
          $("#video_panda_video_id").val(data.id)
          currentFile = null;
        },
        'onError': function(file, message) {
          console.log("onError", message);
          if (!currentFile) {
            $('#upload-error').show(); // upload not accepted
          }
          currentFile = null;
        },
        'onCancel': function(file) {
          console.log("onCancel");
          uploadCancelled = true;
        },
        'onComplete': function(){
          console.log("onComplete");
          if (!uploadCancelled) {
            $("#new_video").submit();
          }
          currentFile = null;
        }
      });

      $("#cancel-btn").click(function() {
        if (currentFile) {
          upl.cancel(currentFile);
          $("#progress-bar").css("width", "0%");
        }
      });

      $('.panda-uploader').attr('accept', 'video/*');

app/views/admin/videos/edit.html.haml
= render 'form'

app/views/admin/videos/new.html.haml
= render 'form'